module.exports = {
    content: [
        './resources/views/**/*.blade.php',
        './app/Filament/**/*.php',
        './resources/js/**/*.js',
        './resources/css/**/*.css'
    ],
    safelist: [
        'fi-absolute-positioning-context',
        'fi-ac-link-action',
        'fi-alert',
        'fi-alert-danger',
        'fi-alert-info',
        'fi-alert-success',
        'fi-alert-warning',
        'fi-badge',
        'fi-badge-active',
        'fi-badge-danger',
        'fi-badge-primary',
        'fi-badge-success',
        'fi-badge-warning',
        'fi-badges-row',
        'fi-btn',
        'fi-btn-danger',
        'fi-btn-primary',
        'fi-btn-secondary',
        'fi-btn-success',
        'fi-card',
        'fi-icon-primary',
        'fi-icon-success',
        'fi-icon-warning',
        'fi-icon-danger',
        'fi-icon-secondary',
        'fi-size-sm',
        'fi-size-md',
        'fi-ta-text-item',
        'fi-ta-text',
        'fi-ta-header-toolbar',
        'fi-ta-selection-indicator',
        'fi-ta-cell',
        'fi-ta-actions',
        'fi-pagination',
        'fi-pagination-overview',
        'fi-pagination-records-per-page-select-ctn',
        'fi-pagination-records-per-page-select',
        'fi-modal',
        'fi-modal-open',
        'fi-modal-close-overlay',
        // Patterns for nested/variant classes:
        { pattern: /^fi-badge/ },
        { pattern: /^fi-alert/ },
        { pattern: /^fi-user/ },
        { pattern: /^fi-color/ },
        { pattern: /^fi-sidebar/ },
        { pattern: /fi-main-text/ },
        { pattern: /fi-badges-row/ },
        { pattern: /fi-table-/ },
        { pattern: /fi-card/ },
        { pattern: /fi-header/ },
        { pattern: /fi-ta-/ },
        { pattern: /fi-modal-/ },
        { pattern: /fi-table-header/ }
    ],
    theme: {
        extend: {}
    },
    plugins: []
};
