name: "Bug Report"
description: "Report a reproducible bug or unexpected behavior"
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: module
    attributes:
      label: Affected Module
      placeholder: e.g. invoices, quotes, payments
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the issue clearly and include expected vs. actual behavior.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a numbered list.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See the error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Your Environment
      placeholder: e.g. Docker, Herd, XAMPP on Windows
