name: "Feature Request"
description: "Propose a new feature or improvement"
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to suggest a feature or enhancement.

  - type: input
    id: area
    attributes:
      label: Affected Area or Module
      placeholder: e.g. invoices, quotes, dashboard, API
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: Explain what problem this feature would solve.

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: Describe your proposed implementation.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes or context
      placeholder: Links, screenshots, alternatives, etc.
